"""
Django settings for bookmyseat project.

Generated by 'django-admin startproject' using Django 5.1.1.
"""

from pathlib import Path
import os
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

# ==========================
# SECURITY CONFIG
# ==========================

SECRET_KEY = os.environ.get('SECRET_KEY', 'unsafe-dev-key')

DEBUG = os.environ.get('DEBUG', 'False').lower() in ('1', 'true', 'yes')

# Render automatically sets this
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]

# Add Render host automatically
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# ==========================
# APPLICATION DEFINITION
# ==========================

INSTALLED_APPS = [
    # your apps…
]

MIDDLEWARE = [
    # your middleware…
]

ROOT_URLCONF = "bookmyseat.urls"

WSGI_APPLICATION = "bookmyseat.wsgi.application"   # ✅ FIXED





