# Generated by Django 5.1.4 on 2025-11-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Documentary', 'Documentary'), ('Drama', 'Drama'), ('Family', 'Family'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Musical', 'Musical'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Sports', 'Sports'), ('Thriller', 'Thriller'), ('War', 'War'), ('Western', 'Western'), ('Biography', 'Biography'), ('History', 'History')], default='Drama', max_length=32),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Malayalam', 'Malayalam'), ('Kannada', 'Kannada'), ('Gujarati', 'Gujarati'), ('Marathi', 'Marathi'), ('Punjabi', 'Punjabi'), ('Bengali', 'Bengali'), ('Urdu', 'Urdu'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('French', 'French'), ('German', 'German'), ('Spanish', 'Spanish'), ('Chinese', 'Chinese'), ('Russian', 'Russian'), ('Arabic', 'Arabic')], default='English', max_length=32),
        ),
    ]
