# Generated by Django 5.1.4 on 2025-11-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='format',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX 3D', 'IMAX 3D')], default='2D', max_length=10),
        ),
    ]
