# Generated by Django 5.2.7 on 2025-12-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_booking_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='parking_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='wheelchair_accessible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='theater',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
        ),
    ]
