# Generated by Django 5.2.7 on 2025-12-07 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_theater_emoji_theater_parking_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid YouTube URL', regex='^(https?\\:\\/\\/)?(www\\.youtube\\.com|youtu\\.be)\\/.+$')]),
        ),
    ]
